version: '2'

services:
  postgres:
    image: turistforeningen/pgrouting-n50:latest

  psql:
    image: turistforeningen/pgrouting-n50:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    links:
      - postgres
    command: /bin/bash
