version: '2'

services:
  postgres:
    image: starefossen/pgrouting:9-2-2

  psql:
    image: starefossen/pgrouting:9-2-2
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    links:
      - postgres
    command: /bin/bash
